# Generated by Django 4.2.6 on 2023-10-17 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cdp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.IntegerField()),
                ('obs_estado', models.CharField(max_length=45)),
                ('justificacion', models.CharField(max_length=80)),
                ('solicitud_cdp_memorando_no_radicado', models.BigIntegerField(db_column='solicitud_cdp_memorando_No_radicado')),
                ('solicitud_cdp_fecha_radicado', models.DateField()),
                ('fecha_cdp', models.DateField()),
                ('valor_cdp', models.FloatField()),
                ('valor_cdp_vf_diciembre_2023', models.IntegerField(db_column='valor_cdp_VF_diciembre_2023')),
                ('cdp_entregado_a', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'cdp',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Datos',
            fields=[
                ('id_datos', models.IntegerField(primary_key=True, serialize=False)),
                ('codigo_bpin', models.IntegerField(db_column='codigo_BPIN')),
                ('nombre_proyecto_de_inversion', models.CharField(max_length=45)),
                ('codigo_ccp', models.CharField(db_column='codigo_CCP', max_length=45)),
                ('objetivo_especifico', models.CharField(max_length=80)),
                ('descripcion_codigo_ccp', models.CharField(db_column='descripcion_codigo_CCP', max_length=45)),
                ('uso_presupuestal', models.CharField(max_length=60)),
                ('recurso', models.IntegerField()),
            ],
            options={
                'db_table': 'datos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InformacionPaaEInsumosEtapaPrevia',
            fields=[
                ('linea_paa', models.CharField(db_column='linea_PAA', max_length=45, primary_key=True, serialize=False)),
                ('objetivo_2023', models.CharField(max_length=200)),
                ('oblligaciones', models.TextField()),
                ('objetivo_2024', models.TextField(blank=True, null=True)),
                ('vifencia_futura', models.CharField(max_length=16)),
                ('codigo_unspsc', models.CharField(db_column='codigo_UNSPSC', max_length=45)),
                ('plazo_meses', models.IntegerField()),
                ('plazo_dias', models.IntegerField(blank=True, null=True)),
                ('mes_inicio', models.CharField(max_length=45)),
                ('fecha_inicio_programada', models.DateField()),
                ('fecha_inicio_programada_copy1', models.DateField()),
                ('valor_honorario_mes', models.IntegerField()),
                ('iva', models.IntegerField()),
                ('valor_honorario_iva', models.IntegerField(blank=True, null=True)),
                ('valor_honorario_2024', models.IntegerField(blank=True, null=True)),
                ('valor_estimado_2023_2024', models.IntegerField(blank=True, db_column='valor_estimado_2023-2024', null=True)),
                ('valor_aprobado_plan_anual_de_adquiciciones_1_semestre_2023', models.IntegerField(blank=True, null=True)),
                ('valor_aprobado_plan_anual_de_adquiciciones_24_07_2023', models.IntegerField(blank=True, db_column='valor_aprobado_plan_anual_de_adquiciciones_24-07-2023', null=True)),
            ],
            options={
                'db_table': 'informacion_paa_e_insumos_etapa_previa',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LegalizacionContratos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_contrato', models.FloatField()),
                ('valor_mes', models.FloatField()),
                ('plazo_mes', models.DecimalField(decimal_places=0, max_digits=10)),
                ('plazo_dias', models.IntegerField(blank=True, null=True)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('nuevo_supervisor', models.CharField(blank=True, max_length=45, null=True)),
                ('no_proceso_secop_ii', models.CharField(blank=True, db_column='No_Proceso_SECOP_II', max_length=45, null=True)),
            ],
            options={
                'db_table': 'legalizacion_contratos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MetasProyecto',
            fields=[
                ('id', models.IntegerField(db_column='ID', primary_key=True, serialize=False)),
                ('metas_proyecto_descripcion', models.TextField()),
            ],
            options={
                'db_table': 'metas_proyecto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PlanAccion',
            fields=[
                ('codigo', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('actividad', models.TextField()),
            ],
            options={
                'db_table': 'plan_accion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProyeccionSegundosContratosPaa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.CharField(blank=True, max_length=24, null=True)),
                ('duracion_meses', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('valor_mes', models.IntegerField(blank=True, null=True)),
                ('proyeccion_18_dic_2023', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'proyeccion_segundos_contratos_paa',
                'managed': False,
            },
        ),
    ]
